[package]
name = "remails"
version = "0.1.0"
edition = "2024"
default-run = "app"
publish = false

[[bin]]
name = "app"
path = "src/bin/app.rs"

[[bin]]
name = "management"
path = "src/bin/management.rs"

[[bin]]
name = "mta"
path = "src/bin/mta.rs"

[[bin]]
name = "retry"
path = "src/bin/retry.rs"

[features]
load-fixtures = []

[dependencies]
anyhow = "1.0.98"
axum = { version = "0.8.4", features = ["macros"] }
axum-extra = { version = "0.10.1", features = ["cookie-private", "typed-header"] }
chrono = { version = "0.4.41", features = ["serde"] }
dotenvy = "0.15.7"
mail-parser = { version = "0.10.2", features = ["serde_support"] }
mail-send = { version = "0.5.1", default-features = false, features = ["builder", "aws-lc-rs", "parser", "dkim"] }
password-auth = "1.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["alloc"] }
smtp-proto = "0.1.6"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio", "tls-rustls-aws-lc-rs", "chrono", "uuid", "macros", "migrate", "json"] }
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["full"] }
tokio-rustls = "0.26.2"
tokio-util = { version = "0.7.15", features = ["io"] }
tower-http = { version = "0.6.6", features = ["trace", "timeout"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-test = "0.2.5"
uuid = { version = "1.17.0", features = ["v4", "serde"] }
url = "2.5.4"
oauth2 = { version = "5.0.0" }
http = "1.3.1"
base64ct = "1.8.0"
reqwest = { version = "0.12.20", default-features = false, features = ["json", "rustls-tls", "cookies", "charset"] }
cookie = "0.18.1"
email_address = "0.2.9"
memory-serve = "1.2.1"
derive_more = { version = "2.0.1" , default-features = false, features = ["from", "display", "deref", "debug", "from_str"]}
rand = "0.9.1"
hickory-resolver = "0.25.2"
aws-lc-rs = "1.13.1"
mail-auth = "0.7.1"
rustls-pemfile = "2.2.0"
humansize = "2.1.3"

[dev-dependencies]
reqwest = { version = "0.12.20", features = ["json"] }
mailcrab = "1.6.0"
serial_test = "3.2.0"

[build-dependencies]
memory-serve = "1.2.0"

[profile.dev.package.sqlx-macros]
opt-level = 3
