[package]
name = "remails"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
dotenvy = "0.15.7"
mail-parser = { version = "0.9.4", features = ["serde_support"] }
mail-send = { version = "0.4.9", default-features = false, features = ["builder", "aws-lc-rs", "parser", "dkim"] }
password-auth = "1.0.0"
rustls-pemfile = "2.1.3"
serde_json = { version = "1.0.128", features = ["alloc"] }
smtp-proto = "0.1.5"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio", "tls-rustls-aws-lc-rs", "chrono", "uuid"] }
thiserror = "1.0.64"
tokio = {version="1.39.2",features=["full"]}
tokio-rustls = "0.26.0"
tokio-tls-upgrade = "0.1.0"
tokio-util = { version = "0.7.12", features = ["io"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-test = "0.2.5"
uuid = { version = "1.10.0", features = ["v4"] }

[profile.dev.package.sqlx-macros]
opt-level = 3

[dev-dependencies]
rand = "0.8.5"
