[package]
name = "remails"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
axum = { version = "0.8.1", features = ["macros"] }
chrono = { version = "0.4.40", features = ["serde"] }
dotenvy = "0.15.7"
mail-parser = { version = "0.10.2", features = ["serde_support"] }
mail-send = { version = "0.5.0", default-features = false, features = ["builder", "aws-lc-rs", "parser", "dkim"] }
password-auth = "1.0.0"
rustls-pemfile = "2.2.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["alloc"] }
smtp-proto = "0.1.6"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio", "tls-rustls-aws-lc-rs", "chrono", "uuid", "macros", "migrate", "json"] }
thiserror = "2.0.12"
tokio = {version="1.44.0",features=["full"]}
tokio-rustls = "0.26.2"
tokio-util = { version = "0.7.13", features = ["io"] }
tower-http = { version = "0.6.2", features = ["trace", "timeout"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-test = "0.2.5"
uuid = { version = "1.15.1", features = ["v4", "serde"] }

[profile.dev.package.sqlx-macros]
opt-level = 3

[dev-dependencies]
rand = "0.9.0"
reqwest = { version = "0.12.13", features = ["json"] }
