[package]
name = "remails"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
mail-parser = { version = "0.9.4", features = ["serde_support"] }
mail-send = { version = "0.4.9", default-features = false, features = ["builder", "aws-lc-rs"] }
rustls-pemfile = "2.1.3"
smtp-proto = "0.1.5"
tokio = {version="1.39.2",features=["full"]}
tokio-rustls = "0.26.0"
tokio-tls-upgrade = "0.1.0"
tokio-util = { version = "0.7.12", features = ["io"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-test = "0.2.5"
uuid = { version = "1.10.0", features = ["v4"] }
