[licenses]
allow = [
    # permissive open source licenses
    "MIT",
    "Apache-2.0",
    "ISC",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "Zlib",
    "OpenSSL",
    "Unicode-3.0",
    "CDLA-Permissive-2.0",
    "bzip2-1.0.6",
    "CC0-1.0",
    # weak copyleft
    "MPL-2.0",
]

confidence-threshold = 0.8
private = { ignore = true }

[bans]
multiple-versions = "allow"

[advisories]
ignore = [
    { id = "RUSTSEC-2024-0436", reason = "utoipa-axum did not provide an updated version yet. Please take a look at https://github.com/juhaku/utoipa/pull/1483" },
]
