[licenses]
allow = [
    # permissive open source licenses
    "MIT",
    "Apache-2.0",
    "ISC",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "Zlib",
    "OpenSSL",
    "NCSA",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "CDLA-Permissive-2.0",
    # weak copyleft
    "MPL-2.0",
    # strong copyleft
    "GPL-2.0",
    "GPL-3.0",
]

confidence-threshold = 0.8

private = { ignore = true }
