services:
  psql:
    image: postgres:16
    environment:
      POSTGRES_USER: remails
      POSTGRES_DB: remails
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: [ '5432:5432' ]

  mailcrab:
    image: marlonb/mailcrab:latest
    ports: [ '1080:1080', '1025:1025' ]