services:
  mailcrab:
    image: marlonb/mailcrab:latest

  remails:
    image: ghcr.io/tweedegolf/remails/app:${TAG}
    ports: [ '3025:3025' ]
    volumes:
      - "./cert.pem:/home/nonroot/cert.pem:ro"
      - "./key.pem:/home/nonroot/key.pem:ro"
    environment:
      TEST_SMTP_ADDR: "smtp://mailcrab:1025"
      SMTP_LISTEN_ADDR: "0.0.0.0:3025"
      SMTP_SERVER_NAME: "remails-dev.tweedegolf-test.nl"
      SMTP_CERT_FILE: "/home/nonroot/cert.pem"
      SMTP_KEY_FILE: "/home/nonroot/key.pem"
      DATABASE_URL: "postgres://remails:${DB_PWD}@postgres:5432/remails"
      GITHUB_OAUTH_REDIRECT_URL: "https://remails-dev.tweedegolf-test.nl/api/oauth/authorize/github"
      SESSION_KEY: "${SESSION_KEY}"
      OAUTH_CLIENT_ID: "${OAUTH_CLIENT_ID}"
      OAUTH_CLIENT_SECRET: "${OAUTH_CLIENT_SECRET}"
      ODOO_BASE_URL: "https://staging-remails.odoo.com/remails"
      ODOO_API_KEY: "${ODOO_API_KEY}"

  caddy:
    image: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config

  postgres:
    image: postgres
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: remails
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: remails
    ports:
      - "5432:5432"

volumes:
  caddy_data:
  caddy_config:
