apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-scaleway-dns
  namespace: cert-manager
spec:
  acme:
    email: support@remails.com
    privateKeySecretRef:
      name: letsencrypt-staging-scaleway-dns
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          webhook:
            groupName: acme.scaleway.com
            solverName: scaleway
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-scaleway-dns
  namespace: cert-manager
spec:
  acme:
    email: support@remails.com
    privateKeySecretRef:
      name: letsencrypt-production-scaleway-dns
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          webhook:
            groupName: acme.scaleway.com
            solverName: scaleway
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-http
spec:
  acme:
    email: support@remails.com
    privateKeySecretRef:
      name: letsencrypt-staging-http
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-http
spec:
  acme:
    email: support@remails.com
    privateKeySecretRef:
      name: letsencrypt-production-http
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx