{{- range .Values.namespaces }}
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: {{ .name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{- include "regcred.registryCredentials" $.Values.docker | nindent 4 }}
---
{{- end -}}
