ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production-http
  ingressClassName: nginx
  hosts:
    - grafana.remails.net
  tls:
    - secretName: grafana-tls-cert
      hosts:
        - grafana.remails.net

persistence:
  enabled: true