apiVersion: apps/v1
kind: Deployment
metadata:
  name: inbound
  namespace: {{ .Release.Namespace }}
  labels:
    app: inbound
    version: {{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.smtp.replicas }}
  selector:
    matchLabels:
      app: inbound
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app: inbound
        environment: {{ .Values.environment }}
        version: {{ .Chart.AppVersion }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: smtp-cert
          secret:
            secretName: smtp-cert
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 75
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - inbound
                topologyKey: topology.kubernetes.io/zone
            - weight: 75
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - inbound
                topologyKey: kubernetes.io/hostname
      containers:
        - name: inbound
          image: "{{ .Values.images.inbound.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.management.pullPolicy }}
          volumeMounts:
            - mountPath: "/etc/smtp-cert"
              name: smtp-cert
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: smtp
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: smtp
            initialDelaySeconds: 15
            periodSeconds: 30
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
            - name: RUST_LOG
              value: {{ .Values.rust_log | quote }}
            - name: SMTP_LISTEN_ADDR
              value: "0.0.0.0:3025"
            - name: SMTP_SERVER_NAME
              value: {{ .Values.smtp.server_name }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: database_url
            - name: SMTP_CERT_FILE
              value: /etc/smtp-cert/tls.crt
            - name: SMTP_KEY_FILE
              value: /etc/smtp-cert/tls.key
            - name: RATE_LIMIT_MINUTES
              value: {{ .Values.smtp.rate_limit_minutes | quote }}
            - name: RATE_LIMIT_MAX_MESSAGES
              value: {{ .Values.smtp.rate_limit_max_messages | quote }}
            - name: MESSAGE_BUS_PORT
              value: {{ .Values.message_bus_port | quote }}
            - name: MESSAGE_BUS_FQDN
              value: message-bus
          ports:
            - containerPort: 3025
              name: smtp