apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: remails-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ printf "letsencrypt-%s-http" .Values.management.certificate_type }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.management.server_name }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: management
                port:
                  name: http
  tls:
    - hosts:
        - {{ .Values.management.server_name }}
      secretName: management-tls-cert

