apiVersion: apps/v1
kind: Deployment
metadata:
  name: management
  labels:
    app: management
    version: {{ include "management.tag" . }}
spec:
  replicas: {{ .Values.management.replicas }}
  selector:
    matchLabels:
      app: management
  template:
    metadata:
      labels:
        app: management
        version: {{ include "management.tag" . }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: management
          image: "{{ .Values.images.management.repository }}:{{ include "management.tag" . }}"
          imagePullPolicy: {{ .Values.images.management.pullPolicy }}
          readinessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: database_url
            - name: RUST_LOG
              value: remails=trace,info
            - name: OAUTH_CLIENT_ID
              value: {{ .Values.github_oauth.client_id }}
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: github_client_secret
            - name: GITHUB_OAUTH_REDIRECT_URL
              value: "https://{{ .Values.management.server_name }}/api/oauth/authorize/github"
            - name: SESSION_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: session_key

          ports:
            - containerPort: 3000
              name: http