apiVersion: apps/v1
kind: Deployment
metadata:
  name: management
  labels:
    app: management
    version: {{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.management.replicas }}
  selector:
    matchLabels:
      app: management
  template:
    metadata:
      labels:
        app: management
        version: {{ .Chart.AppVersion }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: management
          image: "{{ .Values.images.management.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.management.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /api/healthy
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/healthy
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
            - name: SMTP_SERVER_NAME
              value: {{ .Values.smtp.server_name }}
            - name: SMTP_PORT
              value: {{ .Values.smtp.port | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: database_url
            - name: RUST_LOG
              value: remails=trace,info
            - name: OAUTH_CLIENT_ID
              value: {{ .Values.github_oauth.client_id }}
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: github_client_secret
            - name: MONEYBIRD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: moneybird_api_key
            - name: MONEYBIRD_ADMINISTRATION_ID
              value: {{ .Values.moneybird.administration | quote }}
            - name: GITHUB_OAUTH_REDIRECT_URL
              value: "https://{{ .Values.management.server_name }}/api/oauth/authorize/github"
            - name: SESSION_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: session_key

          ports:
            - containerPort: 3000
              name: http