apiVersion: apps/v1
kind: Deployment
metadata:
  name: management
  namespace: {{ .Release.Namespace }}
  labels:
    app: management
    environment: {{ .Values.environment }}
    version: {{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.management.replicas }}
  selector:
    matchLabels:
      environment: {{ .Values.environment }}
      app: management
  template:
    metadata:
      labels:
        environment: {{ .Values.environment }}
        app: management
        version: {{ .Chart.AppVersion }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 75
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - management
                topologyKey: topology.kubernetes.io/zone
            - weight: 75
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - management
                topologyKey: kubernetes.io/hostname
      containers:
        - name: management
          image: "{{ .Values.images.management.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.management.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /api/healthy
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/healthy
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
            - name: SMTP_SERVER_NAME
              value: {{ .Values.smtp.server_name }}
            - name: SMTP_PORTS
              value: {{ join "," .Values.smtp.ports | quote }}
            - name: SPF_INCLUDE
              value: {{ .Values.smtp.spf_include }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: database_url
            - name: RUST_LOG
              value: {{ .Values.rust_log | quote }}
            - name: OAUTH_CLIENT_ID
              value: {{ .Values.github_oauth.client_id }}
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: github_client_secret
            - name: MONEYBIRD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: moneybird_api_key
            - name: MONEYBIRD_ADMINISTRATION_ID
              value: {{ .Values.moneybird.administration | quote }}
            - name: MONEYBIRD_WEBHOOK_URL
              value: {{ .Values.moneybird.webhook_url }}
            - name: GITHUB_OAUTH_REDIRECT_URL
              value: "https://{{ .Values.management.server_name }}/api/oauth/authorize/github"
            - name: SESSION_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: session_key
            - name: DKIM_SELECTOR
              value: {{ .Values.smtp.dkim_selector | quote }}
            - name: MESSAGE_BUS_PORT
              value: {{ .Values.message_bus_port | quote }}
            - name: MESSAGE_BUS_FQDN
              value: message-bus.{{ .Release.Namespace }}.svc.cluster.local

          ports:
            - containerPort: 3000
              name: http