apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-bus
  namespace: {{ .Release.Namespace }}
  labels:
    app: message-bus
    environment: {{ .Values.environment }}
    version: {{ .Chart.AppVersion }}
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: {{ .Values.environment }}
      app: message-bus
  template:
    metadata:
      labels:
        environment: {{ .Values.environment }}
        app: message-bus
        version: {{ .Chart.AppVersion }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: message-bus
          image: "{{ .Values.images.message_bus.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.message_bus.pullPolicy }}
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
            - name: RUST_LOG
              value: {{ .Values.rust_log | quote }}
            - name: MESSAGE_BUS_PORT
              value: {{ .Values.message_bus_port | quote }}
            - name: MESSAGE_BUS_FQDN
              value: message-bus.{{ .Release.Namespace }}.svc.cluster.local

          ports:
            - containerPort: {{ .Values.message_bus_port }}
              name: http