apiVersion: v1
kind: ServiceAccount
metadata:
  name: outbound-service-account
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: outbound-role-{{ .Release.Namespace }}
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: outbound-role-binding
roleRef:
  kind: ClusterRole
  name: outbound-role-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: outbound-service-account
    apiGroup: ""
