apiVersion: v1
kind: ServiceAccount
metadata:
  name: outbound-service-account
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: outbound-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: outbound-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: outbound-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: outbound-service-account
    apiGroup: "v1"
