apiVersion: batch/v1
kind: CronJob
metadata:
  name: retry-failed
  labels:
    app: retry
    version: {{ .Chart.AppVersion }}
spec:
  schedule: {{ .Values.retry.schedule | quote }}
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app: retry
        version: {{ .Chart.AppVersion }}
    spec:
      template:
        spec:
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
              {{- toYaml . | nindent 12 }}
        {{- end }}
          restartPolicy: OnFailure
          containers:
            - name: retry
              image: "{{ .Values.images.retry.repository }}:{{ .Chart.AppVersion }}"
              env:
                - name: VERSION
                  value: {{ .Chart.AppVersion }}
                - name: SMTP_EHLO_DOMAIN
                  value: {{ .Values.smtp.ehlo_domain }}
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: database_url
                - name: MONEYBIRD_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: moneybird_api_key
                - name: MONEYBIRD_ADMINISTRATION_ID
                  value: {{ .Values.moneybird.administration | quote }}
                - name: MONEYBIRD_WEBHOOK_URL
                  value: {{ .Values.moneybird.webhook_url }}
                - name: RUST_LOG
                  value: {{ .Values.rust_log | quote }}
                - name: DKIM_SELECTOR
                  value: {{ .Values.smtp.dkim_selector | quote }}

              imagePullPolicy: {{ .Values.images.retry.pullPolicy }}
